import { useState, useEffect } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import jsPDF from 'jspdf'
import api from '../utils/api'
import { useAuth } from '../context/AuthContext'
import Navbar from '../components/Navbar'
import { ToastContainer } from '../components/Toast'

const levelColor = { Beginner: '#FDCB6E', Intermediate: '#6C63FF', Advanced: '#00D4AA' }

export default function ProfilePreview() {
  const { user } = useAuth()
  const navigate = useNavigate()
  const [profile, setProfile] = useState(null)
  const [loading, setLoading] = useState(true)
  const [linkCopied, setLinkCopied] = useState(false)
  const [generating, setGenerating] = useState(false)

  useEffect(() => {
    api.get('/profile').then(res => { setProfile(res.data); setLoading(false) }).catch(() => setLoading(false))
  }, [])

  const copyLink = () => {
    navigator.clipboard.writeText(window.location.href)
    setLinkCopied(true)
    setTimeout(() => setLinkCopied(false), 2000)
  }

  const downloadPDF = () => {
    if (!profile) return
    setGenerating(true)
    const { user: u, profile: p, experiences, skills, projects, education } = profile
    const doc = new jsPDF('p', 'mm', 'a4')
    const W = 210, M = 20

    // Header gradient area
    doc.setFillColor(108, 99, 255)
    doc.rect(0, 0, W, 50, 'F')

    // Name & headline
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(22)
    doc.setTextColor(255, 255, 255)
    doc.text(u.name || '', M, 22)

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(200, 195, 255)
    if (p.headline) doc.text(p.headline, M, 32)
    if (p.location) doc.text(`📍 ${p.location}  ${p.email || u.email || ''}`, M, 40)

    let y = 60
    const addSection = (title) => {
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(12)
      doc.setTextColor(108, 99, 255)
      doc.text(title.toUpperCase(), M, y)
      doc.setDrawColor(108, 99, 255)
      doc.setLineWidth(0.5)
      doc.line(M, y + 2, W - M, y + 2)
      y += 10
    }

    const addText = (text, indent = M, small = false, color = [70, 70, 90]) => {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(small ? 9 : 10)
      doc.setTextColor(...color)
      const lines = doc.splitTextToSize(text, W - indent - M)
      lines.forEach(l => { doc.text(l, indent, y); y += 5.5 })
    }

    // Summary
    if (p.summary) {
      addSection('About')
      addText(p.summary)
      y += 6
    }

    // Experience
    if (experiences?.length) {
      addSection('Experience')
      experiences.forEach(e => {
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(11)
        doc.setTextColor(30, 30, 60)
        doc.text(e.job_title, M, y)
        y += 6
        addText(`${e.company}  ·  ${e.location || ''}  ·  ${e.start_date} – ${e.is_current ? 'Present' : e.end_date || ''}`, M + 2, true)
        if (e.bullets?.length) {
          e.bullets.slice(0, 3).forEach(b => addText(`• ${b}`, M + 4, true))
        }
        y += 4
      })
    }

    // Skills
    if (skills?.length) {
      addSection('Skills')
      const grouped = {}
      skills.forEach(s => { if (!grouped[s.category]) grouped[s.category] = []; grouped[s.category].push(s.name) })
      Object.entries(grouped).forEach(([cat, names]) => {
        addText(`${cat}: ${names.join(', ')}`, M, true)
      })
      y += 4
    }

    // Projects
    if (projects?.length) {
      addSection('Projects')
      projects.slice(0, 3).forEach(p => {
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(10)
        doc.setTextColor(30, 30, 60)
        doc.text(p.title, M, y); y += 5
        if (p.description) addText(p.description, M + 2, true)
        if (p.tech_stack?.length) addText(`Stack: ${p.tech_stack.join(', ')}`, M + 2, true, [108, 99, 255])
        y += 3
      })
    }

    // Education
    if (education?.length) {
      addSection('Education')
      education.forEach(e => {
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(10)
        doc.setTextColor(30, 30, 60)
        doc.text(`${e.degree} in ${e.field_of_study}`, M, y); y += 5
        addText(`${e.institution}  ·  ${e.start_year}–${e.end_year}  ·  ${e.grade}`, M + 2, true)
        y += 3
      })
    }

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(180, 180, 200)
    doc.text('Generated by HireAI — Smart Recruitment Platform', M, 285)

    doc.save(`${(u.name || 'profile').replace(/ /g, '_')}_HireAI.pdf`)
    setGenerating(false)
  }

  if (loading) return <div className="loading-screen"><div className="spinner" /></div>
  if (!profile) return null

  const { user: u, profile: p, experiences, skills, projects, education } = profile
  const initials = (u?.name || 'U').split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)
  const skillsByCategory = {}
  skills.forEach(s => { if (!skillsByCategory[s.category]) skillsByCategory[s.category] = []; skillsByCategory[s.category].push(s) })

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)' }}>
      <Navbar />
      <ToastContainer />

      <div style={{ maxWidth: 800, margin: '0 auto', padding: '90px 24px 60px' }}>
        {/* Action Bar */}
        <div style={{ display: 'flex', gap: 12, marginBottom: 28, flexWrap: 'wrap', justifyContent: 'flex-end' }}>
          <Link to="/profile/builder" className="btn btn-secondary btn-sm">✏️ Edit Profile</Link>
          <button className="btn btn-secondary btn-sm" onClick={copyLink}>{linkCopied ? '✓ Copied!' : '🔗 Share Link'}</button>
          <button className="btn btn-primary btn-sm" onClick={downloadPDF} disabled={generating}>
            {generating ? <><span className="spinner spinner-sm" />Generating...</> : '⬇ Download PDF'}
          </button>
        </div>

        {/* Completion */}
        <div className="card" style={{ marginBottom: 20 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
            <span style={{ fontSize: '0.9rem', fontWeight: 600 }}>Profile Completion</span>
            <span style={{ color: 'var(--accent)', fontWeight: 700 }}>{p.completion_percent || 0}%</span>
          </div>
          <div className="progress-bar">
            <div className="progress-fill" style={{ width: `${p.completion_percent || 0}%` }} />
          </div>
          {p.is_submitted ? (
            <div style={{ marginTop: 10, color: 'var(--accent)', fontSize: '0.85rem' }}>✓ Profile submitted — visible to recruiters</div>
          ) : (
            <div style={{ marginTop: 10, color: 'var(--text-muted)', fontSize: '0.85rem' }}>Complete your profile and submit to become visible to recruiters</div>
          )}
        </div>

        {/* Profile Header */}
        <div className="card card-elevated" style={{ background: 'linear-gradient(135deg, rgba(108,99,255,0.08), rgba(0,212,170,0.04))', marginBottom: 20 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 24 }}>
            <div className="avatar avatar-xl" style={{ background: 'linear-gradient(135deg, #6C63FF, #00D4AA)', color: 'white', fontSize: '2rem', flexShrink: 0 }}>{initials}</div>
            <div style={{ flex: 1 }}>
              <h1 style={{ fontSize: '1.8rem', marginBottom: 4 }}>{u?.name}</h1>
              <p style={{ color: 'var(--primary-light)', fontWeight: 600, fontSize: '1.05rem', marginBottom: 8 }}>{p.headline}</p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 12, color: 'var(--text-secondary)', fontSize: '0.88rem' }}>
                {p.location && <span>📍 {p.location}</span>}
                {u?.email && <span>📧 {u.email}</span>}
                {p.phone && <span>📱 {p.phone}</span>}
                {p.availability && <span className="badge badge-accent" style={{ marginLeft: 4 }}>{p.availability}</span>}
              </div>
              <div style={{ display: 'flex', gap: 12, marginTop: 10 }}>
                {p.linkedin && <a href={`https://${p.linkedin}`} target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm" style={{ fontSize: '0.78rem' }}>LinkedIn</a>}
                {p.github && <a href={`https://${p.github}`} target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm" style={{ fontSize: '0.78rem' }}>GitHub</a>}
                {p.portfolio && <a href={`https://${p.portfolio}`} target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm" style={{ fontSize: '0.78rem' }}>Portfolio</a>}
              </div>
            </div>
          </div>
        </div>

        {/* Summary */}
        {p.summary && (
          <div className="card" style={{ marginBottom: 20 }}>
            <h2 style={{ fontSize: '1rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 14 }}>About</h2>
            <p style={{ color: 'var(--text)', lineHeight: 1.8 }}>{p.summary}</p>
          </div>
        )}

        {/* Skills */}
        {skills.length > 0 && (
          <div className="card" style={{ marginBottom: 20 }}>
            <h2 style={{ fontSize: '1rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 16 }}>Skills</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
              {Object.entries(skillsByCategory).map(([cat, catSkills]) => (
                <div key={cat}>
                  <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: 8, textTransform: 'uppercase', letterSpacing: 0.5 }}>{cat}</div>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                    {catSkills.map((s, i) => (
                      <div key={i} style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '5px 12px', borderRadius: 100, background: 'var(--bg-input)', border: '1px solid var(--border)', fontSize: '0.85rem' }}>
                        <span style={{ width: 6, height: 6, borderRadius: '50%', background: levelColor[s.level] || 'var(--primary)', flexShrink: 0 }} />
                        {s.name}
                        <span style={{ color: levelColor[s.level], fontSize: '0.72rem', fontWeight: 700 }}>{s.level}</span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Experience */}
        {experiences.length > 0 && (
          <div className="card" style={{ marginBottom: 20 }}>
            <h2 style={{ fontSize: '1rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 16 }}>Experience</h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
              {experiences.map((exp, i) => (
                <div key={i} style={{ position: 'relative', paddingLeft: 20, borderLeft: '2px solid var(--primary)' }}>
                  <div style={{ position: 'absolute', left: -5, top: 4, width: 8, height: 8, borderRadius: '50%', background: exp.is_current ? 'var(--accent)' : 'var(--primary)' }} />
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 8, marginBottom: 4 }}>
                    <div>
                      <h3 style={{ fontSize: '1.05rem', fontWeight: 700, marginBottom: 2 }}>{exp.job_title}</h3>
                      <div style={{ color: 'var(--primary-light)', fontWeight: 600, fontSize: '0.92rem' }}>{exp.company}</div>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                      {exp.is_current && <span className="badge badge-accent" style={{ marginBottom: 4 }}>Current</span>}
                      <div style={{ color: 'var(--text-muted)', fontSize: '0.82rem' }}>{exp.start_date} → {exp.is_current ? 'Present' : exp.end_date}</div>
                      {exp.location && <div style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>📍 {exp.location}</div>}
                    </div>
                  </div>
                  {exp.bullets?.length > 0 && (
                    <ul style={{ paddingLeft: 16, color: 'var(--text-secondary)', fontSize: '0.9rem', lineHeight: 1.8, marginTop: 8 }}>
                      {exp.bullets.map((b, j) => <li key={j}>{b}</li>)}
                    </ul>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Projects */}
        {projects.length > 0 && (
          <div className="card" style={{ marginBottom: 20 }}>
            <h2 style={{ fontSize: '1rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 16 }}>Projects</h2>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 16 }}>
              {projects.map((proj, i) => (
                <div key={i} style={{ background: 'var(--bg-input)', borderRadius: 'var(--radius)', padding: 20, border: '1px solid var(--border)' }}>
                  <h3 style={{ fontSize: '1rem', marginBottom: 8 }}>{proj.title}</h3>
                  <p style={{ color: 'var(--text-secondary)', fontSize: '0.87rem', lineHeight: 1.6, marginBottom: 12 }}>{proj.description}</p>
                  {proj.tech_stack?.length > 0 && (
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, marginBottom: 12 }}>
                      {proj.tech_stack.map((t, j) => <span key={j} className="badge badge-muted">{t}</span>)}
                    </div>
                  )}
                  <div style={{ display: 'flex', gap: 8 }}>
                    {proj.live_url && <a href={`https://${proj.live_url}`} target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm" style={{ fontSize: '0.75rem' }}>🔗 Live</a>}
                    {proj.github_url && <a href={`https://${proj.github_url}`} target="_blank" rel="noreferrer" className="btn btn-secondary btn-sm" style={{ fontSize: '0.75rem' }}>⚙ GitHub</a>}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Education */}
        {education.length > 0 && (
          <div className="card">
            <h2 style={{ fontSize: '1rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: 1, marginBottom: 16 }}>Education</h2>
            {education.map((edu, i) => (
              <div key={i} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 8, marginBottom: 16 }}>
                <div>
                  <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: 2 }}>{edu.degree} in {edu.field_of_study}</h3>
                  <p style={{ color: 'var(--primary-light)', fontSize: '0.9rem' }}>{edu.institution}</p>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem' }}>{edu.start_year} – {edu.end_year}</div>
                  {edu.grade && <div className="badge badge-accent" style={{ marginTop: 4 }}>{edu.grade}</div>}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
